name: Build, Test and Release Avalonia App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Test and Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        if: ${{ hashFiles('**/*Tests.csproj') != '' }}
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish for Windows
        if: matrix.os == 'windows-latest'
        run: |
          dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./publish/win
          7z a artifacts/MyApp-windows.zip ./publish/win/*

      - name: Publish for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o ./publish/linux
          mkdir -p artifacts 
          tar -czvf artifacts/MyApp-linux.tar.gz -C publish/linux .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: artifacts/*


