name: Build and Release Avalonia App

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build for Windows and Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Publish for Windows
        run: |
          dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
          mkdir -p artifacts
          zip -r artifacts/MyApp-windows.zip bin/Release/net9.0/win-x64/publish/

      - name: Publish for Linux (Astra Linux compatible)
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true
          tar -czvf artifacts/MyApp-linux.tar.gz -C bin/Release/net9.0/linux-x64/publish .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
